baseurl = "https://nauar.info/"
languageCode = "en-us"
theme = "hello-friend-ng"
disqusShortname = "nauar"

enableRobotsTXT = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false  
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Arnau Oncins, based in the theme created by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = ["/img/yo.png"]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:arnau.oncins@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nauar/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/arnauoncins"
    
[languages]
  [languages.en]
    title = "Deep dive"
    subtitle = "Arnau Oncins' thoughts"
    homeSubtitle = "Arnau Oncins' thoughts"
    keywords = ""
    copyright = "<a href='https://github.com/nauar' target='_blank'>Arnau Oncins</a>"
    readOtherPosts = "Read other posts"


    [languages.en.params.logo]
      logoText = "rm -rf /"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"



  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/posts/welcome"

